version: '2'

services:

  database:
    image: camptocamp/postgis:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:5.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3.6
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  django:
    image: camptocamp/geonode_django
    build: .
    links:
      - database
      - elasticsearch
      - rabbitmq
      - geoserver
#    uncomment following line for production setup
#    command: gunicorn geonode.wsgi --forwarded-allow-ips=* --workers=3 --bind=0.0.0.0 --worker-tmp-dir=/tmp --access-logfile=- --error-logfile=-
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - C_FORCE_ROOT=1
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_HOST=database
      - DB_PORT=5432
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASSWORD=secret
      - DB_GEONODE_NAME=geonode
      - DB_GEONODE_USER=geonode
      - DB_GEONODE_PASSWORD=secret
      - DB_GEOSERVER_NAME=geoserver
      - DB_GEOSERVER_USER=geoserver
      - DB_GEOSERVER_PASSWORD=secret
    volumes:
      - geonode_config:/mnt/geonode_config
      - geonode_data:/mnt/geonode_data

  celery:
    image: camptocamp/geonode_django
    links:
      - rabbitmq
      - database
      - elasticsearch
    entrypoint: celery
    command:
      - worker
      - --app=geonode.celery_app:app
      - --broker=amqp://guest:guest@rabbitmq:5672/
      - -B
      - -l
      - DEBUG
      - -E
    env_file:
      - ./scripts/docker/env/production/django.env

  consumers:
    image: camptocamp/geonode_django
    links:
      - rabbitmq
      - database
      - elasticsearch
    entrypoint: ["/bin/sh", "-c"]
    command: python manage.py runmessaging
    environment:
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - C_FORCE_ROOT=1
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  geoserver:
    image: camptocamp/geonode_geoserver
    links:
      - database
    ports:
      - "8080:8080"
    volumes:
      - geoserver_datadir:/mnt/geoserver_datadir

volumes:
  rabbitmq_data:
  elasticsearch_data:
  geoserver_datadir:
  geoserver_data:
  postgresql_data:
  geonode_data:
  geonode_config:
